// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzurzDE9H3KpzIxcn9saq-NtHRxcqDKmQ',
    appId: '1:971453665814:web:de7664095ac25f60e91b37',
    messagingSenderId: '971453665814',
    projectId: 'mob3-uas-klp-01-af5c1',
    authDomain: 'mob3-uas-klp-01-af5c1.firebaseapp.com',
    storageBucket: 'mob3-uas-klp-01-af5c1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU_Tz0nHSkHjfn41cMYEm40rwf3ZsJ-JU',
    appId: '1:971453665814:android:7cc1bffdac8a9bf8e91b37',
    messagingSenderId: '971453665814',
    projectId: 'mob3-uas-klp-01-af5c1',
    storageBucket: 'mob3-uas-klp-01-af5c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS8NFFyBL11863ZCkzh3t1xLuin0Jtd74',
    appId: '1:971453665814:ios:c3d5c0fed50546f3e91b37',
    messagingSenderId: '971453665814',
    projectId: 'mob3-uas-klp-01-af5c1',
    storageBucket: 'mob3-uas-klp-01-af5c1.firebasestorage.app',
    iosBundleId: 'com.example.mob3UasKlp01',
  );
}
